// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDizD-oMuCzUT5JKV9nkVVnhSB-fseeHPQ',
    appId: '1:902824532337:web:3731049208bd7e9ccdbed0',
    messagingSenderId: '902824532337',
    projectId: 'kelimemayinlarifirebase',
    authDomain: 'kelimemayinlarifirebase.firebaseapp.com',
    databaseURL: 'https://kelimemayinlarifirebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kelimemayinlarifirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdy-KNAHGGMz0YbDhhfNErq3t4J3svWFs',
    appId: '1:902824532337:android:809a141fcd4ce8a4cdbed0',
    messagingSenderId: '902824532337',
    projectId: 'kelimemayinlarifirebase',
    databaseURL: 'https://kelimemayinlarifirebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kelimemayinlarifirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsk7JgHeSxIpk8SFiiSaApt98wrfR3Dco',
    appId: '1:902824532337:ios:6672acb6fdd8c754cdbed0',
    messagingSenderId: '902824532337',
    projectId: 'kelimemayinlarifirebase',
    databaseURL: 'https://kelimemayinlarifirebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kelimemayinlarifirebase.firebasestorage.app',
    iosBundleId: 'com.example.kelimeMayinlariYeni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsk7JgHeSxIpk8SFiiSaApt98wrfR3Dco',
    appId: '1:902824532337:ios:6672acb6fdd8c754cdbed0',
    messagingSenderId: '902824532337',
    projectId: 'kelimemayinlarifirebase',
    databaseURL: 'https://kelimemayinlarifirebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kelimemayinlarifirebase.firebasestorage.app',
    iosBundleId: 'com.example.kelimeMayinlariYeni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDizD-oMuCzUT5JKV9nkVVnhSB-fseeHPQ',
    appId: '1:902824532337:web:dc03fc6431830be7cdbed0',
    messagingSenderId: '902824532337',
    projectId: 'kelimemayinlarifirebase',
    authDomain: 'kelimemayinlarifirebase.firebaseapp.com',
    databaseURL: 'https://kelimemayinlarifirebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kelimemayinlarifirebase.firebasestorage.app',
  );
}
